### ISSUE TITLE
[request] Add #anchors on subheadings

### ISSUE THREAD

**Issue by degville** [canonical-websites/discourse-docs.snapcraft.io#33]
As requested on the forum:
https://forum.snapcraft.io/t/no-autolink-for-headings-in-topic/7358

The old docs had these, and they're obviously useful for linking.

**Comment by nottrobin** [comment]
This is something that should ideally be added at the point that the Markdown is parsed into HTML, and that happens in Discourse itself.

We *could* post-process the HTML to add these IDs, but that introduces another problem - that forum posts are supposed to be linkable in the same way as the docs site itself - e.g. you might have a link in the navigation to "/t/getting-started/1234#subheading", and that should work inside forum.snapcraft.io just as it should on the site.

So for this reason, I don't think we should solve this here and instead work out how best to solve it in the forum itself.

There is a fair bit of discussion online around this topic, the main conclusion of the current state of things seems to be [here](https://meta.discourse.org/t/deep-linking-to-headings-anchors/47552):

> Unfortunately there is no standard markdown way of creating a heading with an anchor, so you have to use regular HTML for now. Simply create a heading with an id that begins with heading-- like so:
> 
> `<h3 id='heading--link-to-me'>Link to me</h3>`
> 
> And then any time you link to the post, you can add #heading--link-to-me in the URL and it’ll jump directly to that spot once it loads.

It does seem like there's a will to automatically add these IDs inside Discourse posts, but I don't think the solution exists yet.

Would it be okay to use the above solution for now, to create linkable headings? I'll close this for now, assuming we can find a way to solve this satisfactorily in Discourse.

**Comment by sparkiegeek** [comment]
@nottrobin @therealjuan  I've switched https://docs.snapcraft.io/debugging-building-snaps/6274 over to explicit HTML with id's matching the format, and can now deep link as hoped.

But am wondering how we make the ids discoverable?

e.g. https://jujucharms.com/landscape-server/#configuration one can click on the section headers and then copy/paste the deep link for sharing.

another alternative might be an ⚓ shown on hover or similar, but wondering what convention we should adopt

**Comment by nottrobin** [comment]
@sparkiegeek I think that could be a welcome addition. Could you file it as a separate issue? Then the squad can triage it in stand up.

**Comment by Lin-Buo-Ren** [comment]
As the explicit tagging method really is rather a workaround I would like to request to keep this issue open.

**Comment by nottrobin** [comment]
@Lin-Buo-Ren sorry, I don't quite understand the requirement there. Are you saying you want all headings to automatically have IDs?

As mentioned this is not achievable within this Discourse-based system, because all links fundamentally work both within the Discourse forum and in the site. If we simply automatically added IDs to headings in the site, then people would create links to those IDs from within forum pages, that would then fail to link to right place from within the forum.

The proper fix for this is to get Discourse to support automatically generating IDs for headings. And if this were to happen, there wouldn't actually need to be any updates on our end - the IDs would simply be pulled in automatically.

Discourse have mentioned that this would be nice:

> Going forward, we might want to consider auto generating ids for heading tags. Github’s markdown engine does this. For example, <h3>test</h3> automatically becomes <h3 id='test'>test</h3> so you don’t have to worry about adding the id yourself.
> 
> There are downsides to this approach if we do it - in particular it’s difficult to handle headings with the same name. There is more detail here 118 if you are interested in reading more.
(from https://meta.discourse.org/t/deep-linking-to-headings-anchors/47552)

And @coding-horror appears to support the idea:

> I agree that whenever you have headers, you pretty much always want an implicit anchor there too.
(from https://talk.commonmark.org/t/feature-request-automatically-generated-ids-for-headers/115/8)

So it might be possible to advocate for Discourse to implement this feature.

Until there's some sign there might be movement in Discourse support, I don't see how we can do anything our end without creating a mess. So I'm going to leave this closed for now.

**Comment by Lin-Buo-Ren** [comment]
@nottrobin 

Understandable, thanks for your explanation!
